drop table dbeqp.EQP_EVENT_LOG;
CREATE TABLE dbeqp.EQP_EVENT_LOG
(
    EVENT_TIMESTAMP          VARCHAR(36)      NOT NULL,
    EVENT_CRE_DT             TIMESTAMP        NOT NULL,
    FCIL_CDE                 VARCHAR(5)       NOT NULL,
    EVENT_TYPE               VARCHAR(2)       NOT NULL,
    CNTR_NUM                 VARCHAR(11)      NOT NULL,
    EVENT_DT_LOC             TIMESTAMP        NOT NULL,
    EVENT_DT_GMT             TIMESTAMP        ,
    SEAL_NUM                 VARCHAR(12)      ,
    SEAL_TYPE                VARCHAR(2)       ,
    LOAD_EMPTY_IND           CHAR(1)       	,
    SVC_LOOP                 VARCHAR(4)       ,
    VSL_CDE                  VARCHAR(3)       ,
    VOY_NUM                  VARCHAR(3)       ,
    DIR_BOUND                VARCHAR(5)       ,
    LOAD_PORT                VARCHAR(3)       ,
    DSGH_PORT                VARCHAR(3)       ,
    ULTI_LOCA                VARCHAR(60)      ,
    NEXT_LOCA                VARCHAR(5)       ,
    DOC_REF                  VARCHAR(12)      ,
    DOC_TYPE                 CHAR(2)       ,
    GROSS_WT                 NUMERIC(7,2)      ,
    GROSS_WT_UNIT            VARCHAR(3)       ,
    HZ_IND                   BOOLEAN          ,
    REMARKS                  VARCHAR(240)     ,
    CONTRA_ACTION            CHAR(1)       ,
    CNTR_CTRL_PARTY          VARCHAR(2)       ,
    POS_AT_ROUTE             VARCHAR(2)       ,
    NATURE                   VARCHAR(2)       ,
    CNTR_COND                VARCHAR(1)       ,
    CNTR_GRP_CDE       		 VARCHAR(4)       ,
    CNTR_CHK_DIGIT           VARCHAR(2)       ,
    UPD_USER                 VARCHAR(8)       ,
    REC_UPD_DT               TIMESTAMP
);
